apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.redis.name }}
  labels:
   {{- include "redis.labels" . | nindent 4 }}
  namespace: {{ .Values.redis.namespace }}
data:
  redis.conf: |+
    cluster-enabled no
    appendonly yes
    protected-mode yes
    bind 0.0.0.0
    port 0
    tls-port {{ .Values.redis.service.port }}
    tls-cert-file /certs/tls.crt
    tls-key-file /certs/tls.key
    tls-ca-cert-file /certs/ca.crt
---
